name: ci

on:
  workflow_call:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          # registry: # optional
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          # Specifies whether the given registry is ECR (auto, true or false)
          # ecr: # optional, default is auto
          # # Log out from the Docker registry at the end of a job
          # logout: # optional, default is true

      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          tags: ryojikn/app:latest
          # # Path to the Dockerfile
          push: true # optional, default is false
